"""add author column to book

Revision ID: 325d0e3ffb28
Revises: 2e1e9d88af9d
Create Date: 2022-04-01 15:22:23.072475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325d0e3ffb28'
down_revision = '2e1e9d88af9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
