"""empty message

Revision ID: 73c1f8470b04
Revises: f9e86c06ab0d
Create Date: 2022-04-01 12:12:27.193853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c1f8470b04'
down_revision = 'f9e86c06ab0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('isbn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'isbn')
    # ### end Alembic commands ###
