"""add author to book

Revision ID: b416b1966820
Revises: 3a7ada0c18fe
Create Date: 2022-04-01 14:00:06.981039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b416b1966820'
down_revision = '3a7ada0c18fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
