"""empty message

Revision ID: c70ff695bc72
Revises: eec17fb24a4b
Create Date: 2022-04-01 15:07:44.387818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70ff695bc72'
down_revision = 'eec17fb24a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('isbn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'isbn')
    # ### end Alembic commands ###
